#!/usr/bin/env pwsh
$ErrorActionPreference = "Stop"
$repo = "C:\Users\<user>\Documents\ANVIL"
Push-Location $repo
$clangCl = "C:\Program Files\LLVM\bin\clang-cl.exe"
$clangVer = "clang version 22.1.8 (https://github.com/llvm/llvm-project ca7933e47d3a3451d81e72ac174dcb5aa28b59d1)"
$gitHead = (& git rev-parse HEAD 2>$null)
$gitBranch = (& git rev-parse --abbrev-ref HEAD 2>$null)
$status = (& git status --porcelain=v1 2>$null)
$dirty = if ($status) { "DIRTY" } else { "clean" }

function Hash([string]$p){ (Get-FileHash -Algorithm SHA256 -LiteralPath $p).Hash }

$anvil = Hash "build/anvil.exe"
$brotli = Hash "build/brotli_lw.exe"
$bench = Hash "build/anvil_bench.exe"

$info = @()
$info += "# ANVIL pinned build record (POST-FIX BWT backend re-measure)"
$info += "# Generated by tools/build_release.ps1 (bench-normalize, clang-cl pinned)"
$info += "build_time_utc      = $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss UTC' -AsUTC)"
$info += "host                = $env:COMPUTERNAME"
$info += "repo                = $repo"
$info += "git_head            = $gitHead"
$info += "git_branch          = $gitBranch"
$info += "worktree_status     = $dirty"
$info += "worktree_modified   ="
foreach ($line in $status) { $info += "    $line" }
$info += ""
$info += "# --- PINNED COMPILER (same for C and C++) ---"
$info += "compiler_path       = $clangCl"
$info += "compiler_version    = $clangVer"
$info += "c_flags             = -O3 -DNDEBUG"
$info += "cxx_flags           = -O3 -DNDEBUG -std:c++20 -Wno-everything"
$info += "cmake_generator     = Ninja"
$info += ""
$info += "# --- ARTIFACTS (SHA-256) ---  [POST-FIX: arch-bwt bwt_subblock activation + libsais inverse fix, applied in worktree, built 2026-09-07]"
$info += ("{0,-20} = {1}  (.\build\{0})" -f "anvil.exe", $anvil)
$info += ("{0,-20} = {1}  (.\build\{0})" -f "brotli_lw.exe", $brotli)
$info += ("{0,-20} = {1}  (.\build\{0})" -f "anvil_bench.exe", $bench)
$info += ""
$info += "# PRE-FIX (superseded) hashes, for traceability:"
$info += "anvil.exe.PRE-FIX   = DF8B53FF44A9F5ED8F3E96DE5F5CD5AC10D8D437DE56DA1CF8D9955C292BB882"
$info | Set-Content -LiteralPath "build/build-info.txt" -Encoding utf8
Write-Host ($info -join "`n")

$json = @{
  build_time_utc = (Get-Date -AsUTC -Format "o")
  git_head = $gitHead
  git_branch = $gitBranch
  worktree_status = $dirty
  compiler_path = $clangCl
  compiler_version = "$clangVer"
  c_flags = "-O3 -DNDEBUG"
  cxx_flags = "-O3 -DNDEBUG -std:c++20 -Wno-everything"
  note = "POST-FIX BWT backend (bwt_subblock active + libsais inverse fix), built with pinned clang-cl 22.1.8"
  artifacts = @{
    "anvil.exe" = @{ path = "$repo\build\anvil.exe"; sha256 = $anvil }
    "brotli_lw.exe" = @{ path = "$repo\build\brotli_lw.exe"; sha256 = $brotli }
    "anvil_bench.exe" = @{ path = "$repo\build\anvil_bench.exe"; sha256 = $bench }
  }
  pre_fix = @{ "anvil.exe" = "DF8B53FF44A9F5ED8F3E96DE5F5CD5AC10D8D437DE56DA1CF8D9955C292BB882" }
}
$json | ConvertTo-Json -Depth 4 | Set-Content -LiteralPath "build/build-info.json" -Encoding utf8
Write-Host "[done] wrote build-info.txt + build-info.json (POST-FIX)"
Pop-Location
