#!/usr/bin/env python3
"""theory/i8 — MODEL-PHRASE RATE: the entropy floor under a generative model.

The assignment: "formalize a model-based phrase primitive: a reference that
carries a generative model (start, stride, length) plus a sparse residual
stream. Derive the rate: how many bits for the model vs the residuals, and
at what residual density does it stop paying? Give the exact crossover."

THEORY
======
Model: a run of N values of width w bits at byte-offset stride s, generated by

    v_i = a + b*i + e_i,     e_i iid, e_i ~ some innovation distribution

(an arithmetic progression with additive noise).

TWO CODING REGIMES for the residual stream, and the choice between them is
the whole design question:

REGIME 1 — INNOVATION (delta-of-model, "Gorilla-style"):
    transmit d_i = (v_i - v_{i-1}) - b = e_i - e_{i-1}
    rate = N * H(e_i - e_{i-1})
    If e is iid with H(e) = h_e, then H(e_i - e_{i-1}) >= h_e with equality
    ONLY for degenerate cases; generically H(e_i-e_{i-1}) > H(e_i).
    => differencing an iid noise sequence AMPLIFIES entropy (up to +1 bit for
       a symmetric 3-valued e: differences take 5 values).

REGIME 2 — DIRECT RESIDUAL (model + sparse/entropic residual):
    transmit r_i = v_i - (a + b*i) = e_i   directly
    rate = N * H(e_i)     <-- the innovation entropy, the FLOOR

THE CENTRAL POINT: for an arithmetic progression with iid additive
innovation, the correct residual is the INNOVATION e_i itself, i.e. the
residual against the FITTED MODEL, NOT the finite difference. Finite
differencing is the right transform for a RANDOM WALK (where e is the
cumulative sum and deltas are the innovations); it is the WRONG transform
for an AP-with-iid-noise (where the residual to the line IS the innovation).

ANVIL's existing finite-difference invariant (Experiment U) therefore cannot
see synth-arith: it differences and gets H(e_i - e_{i-1}) > H(e_i).

This script MEASURES both regimes on the real corpus files and reports the
exact rate decomposition: model bits + residual bits + control bits.

MEASUREMENT PROTOCOL
====================
- entropy is the SHANNON ENTROPY OF THE EMPIRICAL DISTRIBUTION, computed with
  np.unique counts (no model assumption) — this is the ZERO-ORDER floor. It is
  a LOWER BOUND on what any zero-order coder achieves and an UPPER BOUND on
  what is achievable with context (so: achievable-with-order-0 <= H_emp).
- arithmetic coding overhead ~0.02-0.05% above H; ignored, stated.
- "model bits" counted explicitly.

FALSIFICATION: recompute from tests/corpus/*.bin via
  python prototypes/i8-theory/model_phrase_rate.py
The generator is tests/make_synth_corpus.py (deterministic, seeded) — read it
to check the claimed generative form.
"""
import numpy as np, os, struct, math, collections

CORP = 'tests/corpus'


def H(counts):
    """Shannon entropy in bits of an empirical distribution given counts."""
    c = np.asarray(counts, dtype=np.float64)
    c = c[c > 0]
    p = c / c.sum()
    return float(-(p * np.log2(p)).sum())


def ent(x):
    """Empirical entropy (bits) of an integer array."""
    u, c = np.unique(np.asarray(x), return_counts=True)
    return H(c), len(u)


def load(fn):
    return np.fromfile(os.path.join(CORP, fn), dtype=np.uint8)


def u32le(b, off, n):
    a = b[off:off + 4 * n]
    if len(a) < 4 * n:
        a = np.concatenate([a, np.zeros(4 * n - len(a), np.uint8)])
    return a.view(np.uint32).astype(np.int64)


def fit_ap(v):
    """Least-squares fit v_i = a + b*i. Returns (a, b, resid)."""
    n = len(v)
    i = np.arange(n, dtype=np.float64)
    A = np.stack([np.ones(n), i], axis=1)
    coef, *_ = np.linalg.lstsq(A, v.astype(np.float64), rcond=None)
    a, b = coef
    r = v - (a + b * i)
    return a, b, r


def analyse_ap(name, v, w=32, note=''):
    """Full rate decomposition for an arithmetic-progression column."""
    n = len(v)
    a, b, resid = fit_ap(v)
    resid_i = np.rint(resid).astype(np.int64)
    Hr, kr = ent(resid_i)
    # innovation (finite difference of the residual == second difference)
    d = np.diff(v)
    Hd, kd = ent(d)
    d2 = np.diff(d)
    Hd2, kd2 = ent(d2)
    print(f"    n={n:>7}  fit b={b:>12.4f} a={a:>14.1f}")
    print(f"    residual r_i = v_i-(a+b*i):  H={Hr:6.3f} b/val  (alphabet {kr:>6})  "
          f"-> {n*Hr/8:>10,.0f} B")
    print(f"    1st diff   d_i = v_i-v_(i-1): H={Hd:6.3f} b/val  (alphabet {kd:>6})  "
          f"-> {n*Hd/8:>10,.0f} B   <-- what ANVIL's finite-diff invariant sees")
    print(f"    2nd diff  d2_i = d_i-d_(i-1): H={Hd2:6.3f} b/val  (alphabet {kd2:>6})  "
          f"-> {n*Hd2/8:>10,.0f} B")
    return dict(n=n, b=b, Hr=Hr, kr=kr, Hd=Hd, Hd2=Hd2,
                bytes_resid=n * Hr / 8, bytes_diff=n * Hd / 8)


print("=" * 104)
print("MODEL-PHRASE RATE DECOMPOSITION — synth-arith.bin (8 block-wise u32 AP columns)")
print("=" * 104)
b = load('synth-arith.bin')
print(f"file size {len(b):,} B = {len(b)//4:,} u32 values, {len(b)//4//8000} columns x 8000")
tot_resid = tot_diff = 0.0
cols = []
for c in range(8):
    v = u32le(b, c * 8000 * 4, 8000)
    print(f"\n  column {c}:")
    r = analyse_ap(f'col{c}', v)
    cols.append(r)
    tot_resid += r['bytes_resid']
    tot_diff += r['bytes_diff']

print()
print("  " + "-" * 100)
# model bits: per column, start a (32 bits, but a is recoverable as v_0) and
# stride b. b needs log2 of the range it lives in. MEASURED: strides are
# randint(1,97) => log2(97) = 6.6 bits; but we must transmit them in a
# self-describing way, so budget conservatively.
model_bits_per_col = 32 + 12        # a: 32 bits (or use v_0 verbatim); b: 12 bits budget
model_bytes = 8 * model_bits_per_col / 8
print(f"  MODEL:      8 cols x (a:32 + b:12 bits)                = {model_bytes:>12,.0f} B")
print(f"  RESIDUAL (regime 2, r_i vs fitted line):                = {tot_resid:>12,.0f} B")
print(f"  TOTAL model-phrase wire (order-0 residual coding):      = {tot_resid+model_bytes:>12,.0f} B  "
      f"ratio {(tot_resid+model_bytes)/len(b):.4f}")
print()
print(f"  For contrast — regime 1, first differences (what a delta/")
print(f"  finite-difference transform sees):                      = {tot_diff:>12,.0f} B  "
      f"ratio {tot_diff/len(b):.4f}")
print()
print(f"  brotli-q11 (measured)                                   = {87013:>12,} B  ratio 0.3400")
print(f"  mode-16 ARI-REF harness wire (measured, EXP. Z)         = {89363:>12,} B  ratio 0.3491")
print(f"  ANVIL today                                             = {256022:>12,} B  ratio 1.0000")

print()
print("=" * 104)
print("CROSSOVER: when does a model phrase stop paying?")
print("=" * 104)
print("""
  Let a span of N values of width w be explained EITHER by
    (a) a model phrase:  M bits of model + N*H_r bits of residual, or
    (b) the byte/LZ path: N*w/8 * h_raw bytes (h_raw = entropy ratio of the
        raw bytes under the incumbent coder).

  Model phrase wins iff
        M + N*H_r  <  N*w*h_raw/8
  i.e.  H_r        <  w*h_raw/8  -  M/N                     [bits per value]

  With M = 44 bits/col (a 32 + b 12) amortised over N values:
""")
for N in (64, 256, 1024, 4096, 8000):
    M_over_N = 44.0 / N
    w = 32
    print(f"    N={N:>5}:  M/N = {M_over_N:6.3f} b/val      "
          f"break-even H_r = w*h_raw/8 - {M_over_N:.3f}   "
          f"(h_raw=0.340 -> {32*0.340/8 - M_over_N:6.3f} b/val; "
          f"h_raw=1.000 -> {32*1.0/8 - M_over_N:6.3f} b/val)")
print(f"""
  MEASURED synth-arith H_r ≈ {np.mean([c['Hr'] for c in cols]):.3f} b/val (mean over 8 columns).
  => the model phrase pays by a WIDE margin even at N=64, and the break-even
     residual entropy at N=8000 is ~{32*1.0/8 - 44/8000:.2f} b/val (vs raw) — i.e. the model
     phrase keeps paying until the residual is essentially incompressible.

  THE SHARPER CROSSOVER (residual DENSITY, which is what the assignment asks):
  if instead of coding all N residuals we code only the SPARSE set of nonzero
  ones (candidate mode: model + exception mask + exceptions), let
    rho = fraction of values where the model is exact (r_i == 0).
  Cost = M + N*H_mask(rho) + N*(1-rho)*(H(r | r!=0) + log2(1/(1-rho))_masking)
  Simplified (mask coded at its entropy, exceptions at H_exc):
    Cost(rho) = M + N*[ Hb(rho) + (1-rho)*H_exc ]
  where Hb is the binary entropy. Compare to coding all residuals at H_r:
    Cost_all = M + N*H_r
  Sparse wins iff  Hb(rho) + (1-rho)*H_exc  <  H_r.
""")

# ---- measure rho and H_exc for synth-arith
allr = []
bb = 0
for c in range(8):
    v = u32le(b, c * 8000 * 4, 8000)
    a_, b_, r_ = fit_ap(v)
    allr.append(np.rint(r_).astype(np.int64))
allr = np.concatenate(allr)
rho = float((allr == 0).mean())
nz = allr[allr != 0]
H_exc, k_exc = ent(nz)
H_r_all, _ = ent(allr)
print(f"  MEASURED on synth-arith (64,000 values):")
print(f"    rho (model exact)      = {rho:.4f}   ({int(rho*64000):,} of 64,000)")
print(f"    H_exc (r | r != 0)     = {H_exc:.3f} b   (alphabet {k_exc})")
print(f"    H_r (all residuals)    = {H_r_all:.3f} b")
print(f"    sparse cost  Hb(rho)+(1-rho)*H_exc = {-(rho*math.log2(rho)+(1-rho)*math.log2(1-rho)) if 0<rho<1 else 0:.3f} + {(1-rho)*H_exc:.3f} = "
      f"{(-(rho*math.log2(rho)+(1-rho)*math.log2(1-rho)) if 0<rho<1 else 0) + (1-rho)*H_exc:.3f} b/val")
print(f"    dense  cost  H_r                   = {H_r_all:.3f} b/val")
print(f"    => SPARSE {'WINS' if (-(rho*math.log2(rho)+(1-rho)*math.log2(1-rho)) + (1-rho)*H_exc) < H_r_all else 'LOSES'} "
      f"by {abs(H_r_all - ((-(rho*math.log2(rho)+(1-rho)*math.log2(1-rho))) + (1-rho)*H_exc)):.3f} b/val")

print()
print("=" * 104)
print("synth-timeseries.bin (14 B records: u64 ts +1000+-50, f32 value random walk, u16 id 0..999)")
print("=" * 104)
ts = load('synth-timeseries.bin')
nrec = len(ts) // 14
print(f"{len(ts):,} B / 14 = {nrec:,} records")
recs = ts[:nrec * 14].reshape(nrec, 14)
tsv = recs[:, 0:8].copy().view(np.int64).ravel()      # u64 ts
val = recs[:, 8:12].copy().view(np.float32).ravel()   # f32 value
idv = recs[:, 12:14].copy().view(np.uint16).ravel()   # u16 id
for nm, arr in (('ts (u64)', tsv), ('id (u16)', idv.astype(np.int64))):
    a_, b_, r_ = fit_ap(arr.astype(np.int64))
    Hr, kr = ent(np.rint(r_).astype(np.int64))
    Hd, kd = ent(np.diff(arr.astype(np.int64)))
    Hd2, kd2 = ent(np.diff(np.diff(arr.astype(np.int64))))
    print(f"  {nm:<10} H(resid to line)={Hr:7.3f} b/val ({kr:>6} distinct) | "
          f"H(1st diff)={Hd:6.3f} | H(2nd diff)={Hd2:6.3f}")
# value: f32 -> view as u32 and XOR (Gorilla-style)
vu = recs[:, 8:12].copy().view(np.uint32).ravel().astype(np.int64)
xor = np.bitwise_xor(vu[1:], vu[:-1])
Hx, kx = ent(xor)
print(f"  value f32  H(raw u32)={ent(vu)[0]:7.3f} | H(XOR consecutive)={Hx:7.3f} b/val ({kx} distinct)")
# leading-zero / trailing-zero structure of XOR (Gorilla cases)
def lz(x): return 32 - int(x).bit_length() if x else 32
def tz(x): return (int(x) & -int(x)).bit_length() - 1 if x else 32
lzs = np.array([lz(int(x)) for x in xor])
tzs = np.array([tz(int(x)) for x in xor])
print(f"    XOR leading-zero count: H={ent(lzs)[0]:.3f} b, mean {lzs.mean():.2f}")
print(f"    XOR trailing-zero count: H={ent(tzs)[0]:.3f} b, mean {tzs.mean():.2f}")
# Gorilla: 1 bit if xor==0; else 1+5 bits lz + 6 bits len + mantissa
mant = []
for x, l, t in zip(xor, lzs, tzs):
    if x == 0:
        mant.append(0)
    else:
        mb = 32 - int(l) - int(t)
        mant.append(max(mb, 0))
mant = np.array(mant)
Hmant, _ = ent(mant)
zerofrac = float((xor == 0).mean())
gor = 1.0 + (1 - zerofrac) * (1 + 5 + 6 + Hmant)
print(f"    Gorilla-style per value: zero-frac {zerofrac:.4f} -> "
      f"~{gor:.3f} b/val = {nrec*gor/8:,.0f} B for the value column")

print()
print(f"  MEASURED totals for synth-timeseries:")
ts_a, ts_b, ts_r = fit_ap(tsv.astype(np.float64))
Hts, _ = ent(np.rint(ts_r).astype(np.int64))
print(f"    ts column: model(2 params) + residual H={Hts:.3f} b/val -> {nrec*Hts/8:,.0f} B  "
      f"(vs 8 B/val raw = {nrec*8:,} B)")
print(f"    id column: perfectly cyclic (i mod 1000) -> ~0 bits + period")
print(f"    brotli-q6 (measured)   = 120,669 B  ratio 0.4310")
print(f"    ANVIL hotop-rlzp       = 140,898 B  ratio 0.5032")
